server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
#  datasource:
#    url: jdbc:h2:mem:db_dev;MODE=MYSQL
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/db_test
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
custom:
  fileDirPath: /usr/file